services:
  _defaults:
    autowire: true
    autoconfigure: true

  ContaoSwiperBundle\Renderer\SwiperRenderer:
    public: true

  fritzmg.contao_swiper.renderer:
    alias: ContaoSwiperBundle\Renderer\SwiperRenderer
    public: true
